import {db} from "@/lib/db";import {activeOrganization} from "@/lib/org";import {moneyCents} from "@/lib/utils";
const statusLabel:Record<string,string>={SCHEDULED:"Programadas",EN_ROUTE:"En camino",IN_PROGRESS:"En curso",WAITING_PART:"Esperando repuesto",COMPLETED:"Completadas",CANCELED:"Canceladas"};
export default async function Reports(){
 const{organization}=await activeOrganization();const start=new Date();start.setDate(1);start.setHours(0,0,0,0);
 const[certs,payments,orders,assets,clients]=await Promise.all([
  db.certificate.findMany({where:{organizationId:organization.id,status:{not:"VOID"}},include:{client:true,servicePayments:true,workOrder:{include:{materials:true}}}}),
  db.certificatePayment.findMany({where:{certificate:{organizationId:organization.id},paidAt:{gte:start}}}),
  db.workOrder.findMany({where:{organizationId:organization.id},select:{status:true}}),
  db.asset.count({where:{organizationId:organization.id,status:"ACTIVE"}}),
  db.client.count({where:{organizationId:organization.id}})
 ]);
 const month=certs.filter(c=>c.createdAt>=start);const billed=month.reduce((s,c)=>s+(c.totalAmountCents||0n),0n);const collected=payments.reduce((s,p)=>s+p.amountCents,0n);
 const materials=month.reduce((sum,c)=>sum+(c.workOrder?.materials||[]).reduce((s,m)=>s+(m.unitCostCents?BigInt(Math.round(Number(m.quantity)*1000))*m.unitCostCents/1000n:0n),0n),0n);
 const gross=billed>materials?billed-materials:0n;const grossPct=billed>0n?Math.round(Number(gross*10000n/billed)/100):0;
 const outstanding=certs.reduce((s,c)=>{if(c.totalAmountCents===null)return s;const paid=c.servicePayments.reduce((a,p)=>a+p.amountCents,0n);return s+(c.totalAmountCents>paid?c.totalAmountCents-paid:0n)},0n);
 const perClient=new Map<string,{name:string,count:number,total:bigint,paid:bigint}>();for(const c of certs){const key=c.clientId||"none",x=perClient.get(key)||{name:c.client?.name||"Sin cliente",count:0,total:0n,paid:0n};x.count++;x.total+=c.totalAmountCents||0n;x.paid+=c.servicePayments.reduce((s,p)=>s+p.amountCents,0n);perClient.set(key,x)}
 const top=[...perClient.values()].sort((a,b)=>Number(b.total-a.total)).slice(0,8);const statusCount=orders.reduce<Record<string,number>>((a,o)=>(a[o.status]=(a[o.status]||0)+1,a),{});
 return <><header className="page-head"><div><div className="eyebrow">REPORTES Y RENTABILIDAD</div><h1>La operación en números.</h1><p>Facturación, cobranza, costos directos, margen, clientes y carga de trabajo.</p></div></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Facturado este mes</span><strong>{moneyCents(billed)}</strong><small>{month.length} trabajos documentados</small></div><div className="kpi-card"><span>Cobrado este mes</span><strong>{moneyCents(collected)}</strong><small>Ingresos registrados en caja</small></div><div className="kpi-card"><span>Materiales imputados</span><strong>{moneyCents(materials)}</strong><small>Costos cargados en órdenes cerradas</small></div><div className="kpi-card"><span>Margen bruto operativo</span><strong>{moneyCents(gross)}</strong><small>{grossPct}% sobre facturado · sin incluir otros costos</small></div></section>
 <section className="stats" style={{marginTop:10}}><div className="stat"><span>Saldo pendiente</span><strong>{moneyCents(outstanding)}</strong></div><div className="stat"><span>Clientes</span><strong>{clients}</strong></div><div className="stat"><span>Activos</span><strong>{assets}</strong></div><div className="stat"><span>Órdenes</span><strong>{orders.length}</strong></div></section>
 <div className="two-col" style={{marginTop:14}}><section className="panel"><h2>Principales clientes</h2>{top.length===0?<p className="muted">Sin datos todavía.</p>:top.map((x,i)=>{const balance=x.total>x.paid?x.total-x.paid:0n;return <div key={i} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,padding:"10px 0",borderBottom:"1px solid var(--line)"}}><div><b>{x.name}</b><div className="muted" style={{fontSize:9}}>{x.count} trabajos · saldo {moneyCents(balance)}</div></div><b className="money">{moneyCents(x.total)}</b></div>})}</section><section className="panel"><h2>Órdenes de trabajo</h2>{Object.entries(statusCount).map(([k,v])=><div key={k} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid var(--line)"}}><span>{statusLabel[k]||k}</span><b>{v}</b></div>)}</section></div>
 <div className="report-note"><b>Cómo calcula Constancia el margen</b><p>Margen bruto operativo = importe de las constancias emitidas en el mes menos el costo de materiales y repuestos cargados en sus órdenes vinculadas. No incluye impuestos, sueldos, movilidad ni otros costos indirectos.</p></div></>
}