import Link from "next/link";import {notFound} from "next/navigation";import QRCode from "qrcode";import {db} from "@/lib/db";import {activeOrganization} from "@/lib/org";import {appUrl,moneyCents} from "@/lib/utils";
const statusLabel:Record<string,string>={SCHEDULED:"Programada",EN_ROUTE:"En camino",IN_PROGRESS:"En curso",WAITING_PART:"Esperando repuesto",COMPLETED:"Completada",CANCELED:"Cancelada"};
export default async function AssetDetail({params}:{params:Promise<{id:string}>}){const{id}=await params;const{organization}=await activeOrganization();const a=await db.asset.findFirst({where:{id,organizationId:organization.id},include:{
 client:true,
 certificates:{where:{status:{not:"VOID"}},include:{servicePayments:true},orderBy:{performedAt:"desc"}},
 workOrders:{include:{assignedUser:true,materials:true},orderBy:{createdAt:"desc"},take:12},
 maintenanceContracts:{where:{status:"ACTIVE"},orderBy:{nextVisitAt:"asc"}}
}});if(!a)notFound();
 const publicUrl=appUrl("/a/"+a.publicCode);const qr=await QRCode.toDataURL(publicUrl,{width:320,margin:1,errorCorrectionLevel:"M"});
 const billed=a.certificates.reduce((s,c)=>s+(c.totalAmountCents||0n),0n);const materialCost=a.workOrders.reduce((sum,w)=>sum+w.materials.reduce((s,m)=>s+(m.unitCostCents?BigInt(Math.round(Number(m.quantity)*1000))*m.unitCostCents/1000n:0n),0n),0n);
 const nextService=a.certificates.filter(c=>c.nextServiceAt&&c.nextServiceAt>=new Date()).sort((x,y)=>Number(x.nextServiceAt)-Number(y.nextServiceAt))[0]?.nextServiceAt||null;
 const openOrders=a.workOrders.filter(w=>!["COMPLETED","CANCELED"].includes(w.status));
 return <><header className="page-head"><div><Link className="muted" style={{fontSize:11}} href="/dashboard/activos">← Volver a activos</Link><div className="eyebrow" style={{marginTop:12}}>FICHA 360° · A-{String(a.assetNumber).padStart(5,"0")}</div><h1>{a.name}</h1><p>{a.client.name} · {[a.brand,a.model,a.serialNumber].filter(Boolean).join(" · ")||a.category||"Sin identificación"}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="btn btn-light" href={"/a/"+a.publicCode} target="_blank">Abrir ficha QR</Link><Link className="btn btn-brand" href={"/dashboard/nueva?client="+a.clientId+"&asset="+a.id}>Nueva constancia</Link></div></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Services documentados</span><strong>{a.certificates.length}</strong><small>{openOrders.length} órdenes abiertas</small></div><div className="kpi-card"><span>Facturado asociado</span><strong>{moneyCents(billed)}</strong><small>Histórico del activo</small></div><div className="kpi-card"><span>Materiales imputados</span><strong>{moneyCents(materialCost)}</strong><small>Costos cargados en órdenes</small></div><div className="kpi-card"><span>Próximo service</span><strong>{nextService?nextService.toLocaleDateString("es-AR"):"—"}</strong><small>{a.maintenanceContracts.length} contratos activos</small></div></section>
 <div className="client-360-grid">
  <section className="panel"><div className="panel-title-row"><h2>Identificación</h2></div><dl className="detail-list"><div><dt>Cliente</dt><dd><Link href={"/dashboard/cliente/"+a.clientId}>{a.client.name}</Link></dd></div><div><dt>Categoría</dt><dd>{a.category||"—"}</dd></div><div><dt>Marca / modelo</dt><dd>{[a.brand,a.model].filter(Boolean).join(" · ")||"—"}</dd></div><div><dt>Serie</dt><dd>{a.serialNumber||"—"}</dd></div><div><dt>Ubicación</dt><dd>{a.location||"—"}</dd></div><div><dt>Instalación</dt><dd>{a.installedAt?a.installedAt.toLocaleDateString("es-AR"):"—"}</dd></div><div><dt>Garantía</dt><dd>{a.warrantyUntil?a.warrantyUntil.toLocaleDateString("es-AR"):"—"}</dd></div><div><dt>Estado</dt><dd>{a.status}</dd></div></dl></section>
  <section className="panel"><div className="panel-title-row"><h2>QR físico</h2></div><div className="asset-qr-panel"><img src={qr} width={150} height={150} alt={"QR del activo "+a.name}/><div><b>Identidad digital del equipo</b><p>Imprimilo y pegalo en la máquina, vehículo o instalación. Abre la ficha pública verificable.</p><a className="btn btn-light" href={qr} download={"constancia-activo-"+a.assetNumber+".png"}>Descargar QR</a></div></div></section>
  <section className="panel"><div className="panel-title-row"><h2>Órdenes recientes</h2><Link href="/dashboard/ordenes">Ver todas</Link></div>{a.workOrders.length===0?<p className="muted">Sin órdenes todavía.</p>:a.workOrders.slice(0,7).map(w=><Link className="mini-list-row" href={"/dashboard/orden/"+w.id} key={w.id}><div><b>OT-{String(w.sequentialNumber).padStart(5,"0")} · {w.title}</b><small>{w.assignedUser?.name||"Sin técnico"}{w.startedAt?" · iniciado "+w.startedAt.toLocaleDateString("es-AR"):""}</small></div><span className={"pill wo-"+w.status.toLowerCase()}>{statusLabel[w.status]||w.status}</span></Link>)}</section>
  <section className="panel"><div className="panel-title-row"><h2>Contratos / mantenimiento</h2></div>{a.maintenanceContracts.length===0?<p className="muted">No hay contratos activos para este equipo.</p>:a.maintenanceContracts.map(x=><div className="mini-list-row" key={x.id}><div><b>{x.name}</b><small>Cada {x.frequencyDays} días{x.nextVisitAt?" · próxima "+x.nextVisitAt.toLocaleDateString("es-AR"):""}</small></div>{x.monthlyAmountCents&&<b className="money">{moneyCents(x.monthlyAmountCents)}/mes</b>}</div>)}</section>
 </div>
 <section className="table-card"><div className="panel-table-head"><div><b>Historial técnico completo</b><span>Services y constancias asociadas al activo</span></div></div>{a.certificates.length===0?<p className="muted" style={{padding:24}}>Este activo todavía no tiene constancias.</p>:a.certificates.map(c=>{const paid=c.servicePayments.reduce((s,p)=>s+p.amountCents,0n);const balance=c.totalAmountCents===null?null:c.totalAmountCents>paid?c.totalAmountCents-paid:0n;return <Link href={"/dashboard/constancia/"+c.id} className="table-row" key={c.id}><span className="money">#{String(c.sequentialNumber).padStart(6,"0")}</span><div><b>{c.serviceTitle}</b><div className="muted">{c.technicianName||"Sin técnico"}{c.nextServiceAt?" · próximo "+c.nextServiceAt.toLocaleDateString("es-AR"):""}</div></div><span>{c.performedAt.toLocaleDateString("es-AR")}</span><span className={"pill "+(balance&&balance>0n?"pending":"paid")}>{balance&&balance>0n?"Saldo "+moneyCents(balance,c.currency):c.totalAmountCents===null?"Sin importe":"Al día"}</span></Link>})}</section></>}