import Link from "next/link";
import {ArrowRight,BarChart3,BriefcaseBusiness,CalendarDays,Camera,Check,ClipboardCheck,FileCheck2,FileText,HardHat,History,MapPin,PackageCheck,QrCode,ReceiptText,RefreshCcw,ShieldCheck,Smartphone,UsersRound,Wrench} from "lucide-react";
import {PublicNav} from "@/components/PublicNav";import {Footer} from "@/components/Footer";import {money} from "@/lib/utils";import {PLAN_INFO} from "@/lib/plans";

const modules=[
 {i:UsersRound,t:"Clientes y portal",d:"Centralizá datos, equipos, trabajos, constancias y acceso privado para cada cliente."},
 {i:PackageCheck,t:"Equipos y activos",d:"ID interno, marca, modelo, serie, ubicación, garantía, QR físico e historial por equipo."},
 {i:ClipboardCheck,t:"Órdenes de trabajo",d:"Programá, asigná técnicos, definí prioridades y seguí cada trabajo hasta completarlo."},
 {i:CalendarDays,t:"Agenda operativa",d:"Próximos trabajos, services y contratos en una misma vista para ordenar el día a día."},
 {i:FileText,t:"Presupuestos",d:"Armá ítems y precios, compartí un link y convertí presupuestos aprobados en órdenes."},
 {i:RefreshCcw,t:"Contratos y abonos",d:"Registrá frecuencia, próxima visita, importe mensual, cliente y activo asociado."},
 {i:HardHat,t:"Ejecución en campo",d:"Checklist, inicio y fin, GPS, notas técnicas y evidencia fotográfica Antes / Durante / Después."},
 {i:FileCheck2,t:"Constancia verificable",d:"Firma, fotos, PDF, QR público, garantía, próximo service y trazabilidad del trabajo."},
 {i:ReceiptText,t:"Caja y cobros",d:"Registrá efectivo, transferencia, Mercado Pago, tarjetas, cheques y saldos pendientes."},
 {i:BarChart3,t:"Reportes",d:"Facturado, cobrado, deuda, clientes principales, activos y estado de las órdenes."},
 {i:Smartphone,t:"App instalable",d:"Usala desde el celular como una app y mantené el trabajo operativo incluso en campo."},
 {i:ShieldCheck,t:"Historial confiable",d:"Cada servicio queda relacionado con cliente, activo, técnico, evidencia y comprobante."}
];
const flow=["Presupuesto","Aprobación","Orden","Agenda","Técnico","Checklist + GPS","Fotos","Firma","Constancia","Cobro","Próximo service"];
const faqs=[
 ["¿Constancia sirve solamente para hacer comprobantes?","No. Constancia organiza el ciclo completo de una empresa de servicios: clientes, activos, presupuestos, órdenes, agenda, técnicos, ejecución en campo, constancias, cobros, contratos y reportes."],
 ["¿Puedo llevar el historial de cada equipo?","Sí. Cada activo tiene identificación propia y puede guardar marca, modelo, número de serie, ubicación, instalación, garantía, órdenes y constancias relacionadas."],
 ["¿Cómo trabaja un técnico desde el celular?","Puede abrir la orden asignada, iniciar el trabajo, completar el checklist, registrar ubicación, cargar fotos Antes / Durante / Después, dejar notas y finalizar la ejecución."],
 ["¿El checklist puede ser obligatorio?","Sí. Cuando una plantilla tiene checklist, la ejecución no permite cerrar el trabajo desde el flujo de campo hasta completar los puntos requeridos."],
 ["¿Las constancias se pueden verificar?","Sí. Cada constancia emitida tiene identificación única y acceso verificable. También puede incluir PDF, QR, fotos, firma, próximo service, garantía e información de cobro."],
 ["¿Puedo enviar presupuestos al cliente?","Sí. Podés crear presupuestos con ítems, cantidades y precios, compartirlos mediante un enlace y luego convertir el trabajo aprobado en una orden."],
 ["¿Sirve para mantenimientos recurrentes?","Sí. Los contratos y abonos permiten registrar frecuencia, próxima visita, importe mensual y asociarlos a un cliente y, cuando corresponde, a un activo."],
 ["¿Puedo registrar pagos parciales?","Sí. Constancia permite registrar cobros y mantener visible el total, lo abonado y el saldo pendiente de los trabajos."],
 ["¿El cliente tiene acceso a su información?","Sí. El portal del cliente concentra sus equipos, historial y constancias verificables mediante un acceso privado."],
 ["¿Se puede instalar como app?","Sí. Constancia está preparada como PWA instalable para trabajar desde celular o computadora sin depender de una app pesada de escritorio."],
 ["¿Para qué rubros sirve?","Está pensada para empresas y profesionales que realizan servicios: mantenimiento, climatización, electricidad, talleres, instalaciones, limpieza técnica, fumigación, servicios industriales y trabajo en campo, entre otros."],
 ["¿Tengo que cargar una tarjeta para probarla?","No. Podés empezar con el plan gratuito y conocer el flujo antes de pasar a un plan pago."]
];
export default function Home(){return <><a className="skip-link" href="#contenido">Saltar al contenido</a><PublicNav/><main id="contenido">
<section className="container hero hero-v2"><div><div className="eyebrow">OPERACIÓN DE SERVICIOS, DE PUNTA A PUNTA</div><h1>Del presupuesto al próximo service.</h1><p className="lead">Constancia conecta clientes, equipos, órdenes, técnicos, evidencia, comprobantes y cobros en un solo lugar. Menos chats sueltos. Más trazabilidad.</p><div className="hero-actions"><Link href="/registro" className="btn btn-brand">Empezar gratis <ArrowRight size={15}/></Link><Link href="/demo" className="btn btn-light">Ver una constancia</Link></div><div className="hero-proof"><span><Check size={14}/> Sin tarjeta</span><span><Smartphone size={14}/> Instalable</span><span><QrCode size={14}/> QR verificable</span></div></div>
<div className="product-window"><div className="window-top"><span/><span/><span/><b>Constancia · Operaciones</b></div><div className="mini-stats"><div><small>ÓRDENES ABIERTAS</small><strong>12</strong></div><div><small>HOY</small><strong>5</strong></div><div><small>COBRADO</small><strong>$1.24M</strong></div></div><div className="job-preview"><div className="job-head"><div><small>OT-00142</small><b>Mantenimiento preventivo</b></div><span className="pill wo-in_progress">EN CURSO</span></div><div className="job-meta"><span><UsersRound size={13}/> Metalúrgica Norte</span><span><Wrench size={13}/> Compresor Atlas</span><span><MapPin size={13}/> GPS registrado</span></div><div className="progress-label"><span>Checklist de ejecución</span><b>4/5</b></div><div className="progress-track"><i/></div><div className="evidence"><div><Camera size={17}/><span>ANTES</span><b>3 fotos</b></div><div><Camera size={17}/><span>DURANTE</span><b>4 fotos</b></div><div><Camera size={17}/><span>DESPUÉS</span><b>2 fotos</b></div></div></div><div className="window-foot"><span>Cliente → Equipo → OT → Evidencia → Constancia</span><span className="live-dot">Sincronizado</span></div></div></section>
<div className="container trust trust-v2"><b>Una sola operación.</b> Service técnico · climatización · mantenimiento industrial · talleres · instalaciones · fumigación · limpieza técnica · trabajo en campo.</div>

<section id="como-funciona" className="section section-white"><div className="container"><div className="section-intro"><div><div className="eyebrow">EL SISTEMA COMPLETO</div><h2>Todo conectado.</h2></div><p>Lo que antes vivía separado entre WhatsApp, planillas, PDFs y memoria del equipo, ahora sigue un mismo recorrido.</p></div><div className="flow">{flow.map((x,i)=><div className="flow-step" key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b>{i<flow.length-1&&<ArrowRight size={14}/>}</div>)}</div></div></section>

<section id="funciones" className="section"><div className="container"><div className="section-intro"><div><div className="eyebrow">CONSTANCIA 2.1</div><h2>Más que un comprobante.</h2></div><p>Un sistema operativo para empresas que venden, programan, ejecutan y vuelven a vender servicios.</p></div><div className="feature-grid">{modules.map(({i:I,t,d})=><article className="feature-card" key={t}><div className="iconbox"><I size={20}/></div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

<section className="section dark-section"><div className="container"><div className="section-intro"><div><div className="eyebrow">PARA EL TRABAJO REAL</div><h2>El técnico documenta. La empresa controla.</h2></div><p>La evidencia nace en el lugar del trabajo y queda asociada a la orden, no perdida en el teléfono de alguien.</p></div><div className="role-grid"><article><HardHat size={24}/><h3>Técnico</h3><p>Orden asignada, checklist, GPS, fotos por etapa, notas, horarios y cierre del trabajo.</p></article><article><BriefcaseBusiness size={24}/><h3>Administración</h3><p>Agenda, presupuestos, contratos, materiales, cobros, saldos, activos y reportes.</p></article><article><UsersRound size={24}/><h3>Cliente</h3><p>Presupuesto para aprobar, portal privado, historial y constancias profesionales verificables.</p></article></div></div></section>

<section className="section section-white"><div className="container split-story"><div><div className="eyebrow">TRAZABILIDAD</div><h2>Un equipo deja de ser “ese equipo”.</h2><p className="lead-small">Cada activo tiene identidad e historial. Sabés qué se hizo, cuándo, quién lo hizo, qué materiales se usaron y cuál es el próximo paso.</p><ul className="clean-list"><li><Check/> ID interno y QR individual</li><li><Check/> Marca, modelo, serie y ubicación</li><li><Check/> Instalación y garantía</li><li><Check/> Historial de órdenes y constancias</li><li><Check/> Contratos y próximos mantenimientos</li></ul></div><div className="asset-card"><div className="asset-code">A-00027</div><div className="asset-qr">QR</div><small>EQUIPO</small><h3>Compresor principal</h3><dl><div><dt>Marca / modelo</dt><dd>Atlas · GA 15</dd></div><div><dt>Serie</dt><dd>AC-845921</dd></div><div><dt>Ubicación</dt><dd>Planta 1</dd></div><div><dt>Próximo service</dt><dd>18/11/2026</dd></div></dl><span className="status">ACTIVO · HISTORIAL AL DÍA</span></div></div></section>

<section id="precios" className="section"><div className="container"><div className="section-intro"><div><div className="eyebrow">PRECIOS</div><h2>Empezá chico. Operá en serio.</h2></div><p>Probalo gratis y escalá cuando el volumen de tu operación lo necesite.</p></div><div className="pricing pricing-v2">{Object.entries(PLAN_INFO).map(([key,p])=><div className={`card pricecard ${key==="PRO"?"popular":""}`} key={key}>{key==="PRO"&&<span className="badge">MÁS ELEGIDO</span>}<b>{p.name}</b><div className="price">{p.monthly?money(p.monthly):"$0"}</div><div className="muted price-sub">por mes</div><ul className="list"><li>✓ {p.certificateLimit} constancias/mes</li><li>✓ QR + PDF verificable</li><li>✓ Clientes, activos y órdenes</li><li>✓ Presupuestos y operación</li><li>{p.reminders?"✓":"—"} Recordatorios</li><li>{p.team?"✓":"—"} Trabajo en equipo</li></ul><Link href="/registro" className={`btn ${key==="PRO"?"btn-brand":"btn-light"}`}>Empezar</Link></div>)}</div></div></section>

<section id="faq" className="section section-white"><div className="container faq-wrap"><div className="faq-title"><div className="eyebrow">PREGUNTAS FRECUENTES</div><h2>Antes de empezar.</h2><p>Lo importante sobre cómo se usa Constancia en una operación real.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="section final-cta"><div className="container"><div><div className="eyebrow">MENOS DESORDEN. MÁS CONTROL.</div><h2>Tu próximo trabajo puede quedar documentado de punta a punta.</h2></div><Link href="/registro" className="btn btn-brand">Crear cuenta gratis <ArrowRight size={15}/></Link></div></section>
</main><Footer/></>}