"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {CheckCircle2,MessageCircle,Send} from "lucide-react";
type Thread={id:string;name:string|null;email:string|null;subject:string|null;status:string;lastMessageAt:string;organization:{name:string}|null;messages:{id:string;sender:string;body:string;createdAt:string}[]};
export function AdminSupportInbox({threads}:{threads:Thread[]}){
 const r=useRouter();const[open,setOpen]=useState<string|null>(threads[0]?.id||null);const[busy,setBusy]=useState<string|null>(null);
 async function reply(id:string,e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const message=String(f.get("message")||"").trim();if(!message)return;setBusy(id);const x=await fetch("/api/admin/support/"+id+"/reply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message})});setBusy(null);if(x.ok){(e.currentTarget as HTMLFormElement).reset();r.refresh()}}
 async function close(id:string){setBusy(id);await fetch("/api/admin/support/"+id+"/close",{method:"POST"});setBusy(null);r.refresh()}
 return <section className="panel admin-support"><div className="panel-title-row"><div><h2>Soporte</h2><span className="muted">Consultas del panel y de la web</span></div><span className="pill">{threads.filter(t=>t.status!=="CLOSED").length} abiertas</span></div>
 {threads.length===0?<div className="empty-state">No hay consultas de soporte.</div>:threads.map(t=><article className={"admin-support-thread "+(open===t.id?"open":"")} key={t.id}><button className="admin-support-summary" onClick={()=>setOpen(open===t.id?null:t.id)}><div><b>{t.subject||"Consulta"}</b><span>{t.name||"Usuario"} · {t.email||t.organization?.name||"Cuenta"} · {new Date(t.lastMessageAt).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"})}</span></div><span className={"pill "+(t.status==="CLOSED"?"paid":"pending")}>{t.status==="OPEN"?"Nueva":t.status==="WAITING_USER"?"Respondida":"Cerrada"}</span></button>
 {open===t.id&&<div className="admin-support-body"><div className="admin-support-messages">{t.messages.map(m=><div className={"support-msg "+(m.sender==="ADMIN"?"admin":"user")} key={m.id}><span>{m.sender==="ADMIN"?"Constancia":"Cliente"}</span><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"})}</small></div>)}</div>{t.status!=="CLOSED"?<form onSubmit={e=>reply(t.id,e)} className="admin-support-reply"><textarea className="textarea" name="message" placeholder="Escribí la respuesta..." required/><div className="actions"><button type="button" className="btn btn-light" disabled={busy===t.id} onClick={()=>close(t.id)}><CheckCircle2 size={13}/>Cerrar</button><button className="btn btn-brand" disabled={busy===t.id}>{busy===t.id?"Guardando...":<><Send size={13}/>Responder</>}</button></div></form>:<div className="success"><MessageCircle size={14}/> Conversación cerrada.</div>}</div>}</article>)}</section>
}