"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {Archive,ChevronDown,ExternalLink,PackagePlus,Plus,QrCode,Search,X} from "lucide-react";

type Client={id:string;name:string};
type Asset={id:string;assetNumber:number;publicCode:string;name:string;category:string|null;brand:string|null;model:string|null;serialNumber:string|null;location:string|null;status:string;client:{id:string;name:string};_count:{certificates:number;workOrders:number}};
const blank={clientId:"",name:"",category:"",brand:"",model:"",serialNumber:"",location:"",notes:"",installedAt:"",warrantyUntil:""};

export function AssetManager({clients}:{clients:Client[]}){
 const r=useRouter();const[assets,setAssets]=useState<Asset[]>([]);const[form,setForm]=useState(blank);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[show,setShow]=useState(false);const[q,setQ]=useState("");
 async function load(){const x=await fetch("/api/assets");const j=await x.json();const rows=j.assets||[];setAssets(rows);if(rows.length===0&&clients.length>0)setShow(true)}
 useEffect(()=>{load();if(location.hash==="#nuevo")setShow(true)},[]);
 const filtered=useMemo(()=>assets.filter(a=>[a.name,a.client.name,a.category,a.brand,a.model,a.serialNumber,a.location].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase())),[assets,q]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await res.json();if(!res.ok)throw new Error(j.error);setForm(blank);setShow(false);await load();r.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar el equipo.")}finally{setBusy(false)}}
 async function retire(id:string){if(!confirm("¿Retirar este equipo? El historial queda guardado."))return;await fetch("/api/assets/"+id,{method:"DELETE"});await load();r.refresh()}
 if(clients.length===0)return <section className="prerequisite-card"><div className="empty-icon"><PackagePlus size={23}/></div><div><span className="eyebrow">PRIMERO UN CLIENTE</span><h2>¿De quién es el equipo?</h2><p>Antes de cargar una máquina, vehículo o instalación, necesitás crear el cliente.</p></div><Link className="btn btn-brand" href="/dashboard/clientes#nuevo">Crear cliente</Link></section>;
 return <div className="manager-v3"><section className="manager-toolbar"><div><b>{assets.length} equipo{assets.length===1?"":"s"} activo{assets.length===1?"":"s"}</b><span>Solo cargalos si necesitás historial por máquina, vehículo o instalación.</span></div><button className="btn btn-brand" onClick={()=>setShow(true)}><Plus size={14}/>Agregar equipo</button></section>
 {show&&<form id="nuevo" className="panel form simple-form-card" onSubmit={submit}><div className="simple-form-head"><div className="simple-form-number"><PackagePlus size={18}/></div><div><span>NUEVO EQUIPO</span><h2>¿Qué equipo querés identificar?</h2><p>Cliente y nombre son suficientes. El resto es opcional.</p></div><button type="button" className="icon-close" onClick={()=>{setShow(false);setForm(blank)}}><X size={17}/></button></div>
 <div className="simple-fields"><label className="field field-big">Cliente<select className="select" required value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Elegí un cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field field-big">Nombre del equipo<input className="input" required placeholder="Ej. Aire oficina / Camión 12 / Bomba 3" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">Tipo <small>opcional</small><input className="input" placeholder="Aire, vehículo, bomba..." value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field">Ubicación <small>opcional</small><input className="input" placeholder="Planta, oficina, patente..." value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></div>
 <details className="optional-fields"><summary>Agregar marca, modelo, serie, fechas o notas <ChevronDown size={14}/></summary><div className="form-grid"><label className="field">Marca<input className="input" value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label className="field">Modelo<input className="input" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label className="field">N.º de serie<input className="input" value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})}/></label><label className="field">Instalado el<input className="input" type="date" value={form.installedAt} onChange={e=>setForm({...form,installedAt:e.target.value})}/></label><label className="field">Garantía hasta<input className="input" type="date" value={form.warrantyUntil} onChange={e=>setForm({...form,warrantyUntil:e.target.value})}/></label><label className="field full">Notas<textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></details>{error&&<div className="error">{error}</div>}<div className="simple-form-actions"><button className="btn btn-light" type="button" onClick={()=>setShow(false)}>Cancelar</button><button className="btn btn-brand" disabled={busy}>{busy?"Guardando...":"Guardar equipo"}</button></div></form>}
 <section className="manager-list-v3"><div className="manager-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar equipo, cliente, marca o serie..."/></div>{filtered.length===0?<div className="simple-empty large"><div className="empty-icon"><PackagePlus size={22}/></div><b>{assets.length===0?"No cargaste equipos todavía.":"No encontramos coincidencias."}</b></div>:filtered.map(a=><article className="simple-list-row" key={a.id}><Link className="simple-list-main" href={"/dashboard/activo/"+a.id}><div className="asset-badge">A-{String(a.assetNumber).padStart(3,"0")}</div><div><b>{a.name}</b><span>{a.client.name}{a.category?" · "+a.category:""}</span><small>{[a.brand,a.model,a.serialNumber,a.location].filter(Boolean).join(" · ")||"Sin datos extra"}</small></div></Link><div className="row-meta"><span>{a._count.workOrders} trabajos</span><span>{a._count.certificates} constancias</span></div><div className="row-actions"><Link className="btn btn-light" href={"/dashboard/activo/"+a.id}><ExternalLink size={13}/></Link><Link className="btn btn-light" href={"/a/"+a.publicCode} target="_blank"><QrCode size={13}/></Link><button className="btn btn-light danger-quiet" onClick={()=>retire(a.id)}><Archive size={13}/></button></div></article>)}</section></div>
}