"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";import {ArrowRight,CheckCircle2,ChevronDown,ExternalLink,Pencil,Plus,Search,Trash2,UserPlus,X} from "lucide-react";
type Client={id:string;name:string;email:string|null;phone:string|null;taxId:string|null;address:string|null;notes:string|null};
const blank={name:"",email:"",phone:"",document:"",address:"",notes:""};
export function ClientManager(){
 const r=useRouter();const[clients,setClients]=useState<Client[]>([]);const[form,setForm]=useState(blank);const[edit,setEdit]=useState<string|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[show,setShow]=useState(false);const[q,setQ]=useState("");const[created,setCreated]=useState<{id:string;name:string}|null>(null);
 async function load(){const x=await fetch("/api/clients");const j=await x.json();const rows=j.clients||[];setClients(rows);if(rows.length===0)setShow(true)}
 useEffect(()=>{load();if(location.hash==="#nuevo")setShow(true)},[]);
 const filtered=useMemo(()=>clients.filter(c=>[c.name,c.email,c.phone,c.taxId].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase())),[clients,q]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch(edit?"/api/clients/"+edit:"/api/clients",{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await res.json();if(!res.ok)throw new Error(j.error);if(!edit&&j.client)setCreated({id:j.client.id,name:j.client.name});setForm(blank);setEdit(null);setShow(false);await load();r.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar el cliente.")}finally{setBusy(false)}}
 function start(c:Client){setEdit(c.id);setShow(true);setForm({name:c.name,email:c.email||"",phone:c.phone||"",document:c.taxId||"",address:c.address||"",notes:c.notes||""});window.scrollTo({top:0,behavior:"smooth"})}
 function cancel(){setEdit(null);setForm(blank);setError("");setShow(false)}
 async function del(id:string){if(!confirm("¿Eliminar este cliente? Las constancias que ya existen se conservan."))return;await fetch("/api/clients/"+id,{method:"DELETE"});await load();r.refresh()}
 return <div className="manager-v3">{created&&<section className="next-step-success"><div><CheckCircle2 size={18}/><div><b>{created.name} ya está cargado.</b><span>El siguiente paso más común es crearle un trabajo.</span></div></div><div><Link className="btn btn-brand" href={"/dashboard/ordenes?client="+encodeURIComponent(created.id)+"#nuevo"}>Crear trabajo <ArrowRight size={13}/></Link><button className="btn btn-light" type="button" onClick={()=>setCreated(null)}>Después</button></div></section>
  <section className="manager-toolbar"><div><b>{clients.length} cliente{clients.length===1?"":"s"}</b><span>Guardá solo lo que tengas. Después podés completar el resto.</span></div><button className="btn btn-brand" onClick={()=>{setEdit(null);setForm(blank);setShow(true)}}><Plus size={14}/>Agregar cliente</button></section>
  {show&&<form id="nuevo" className="panel form simple-form-card" onSubmit={submit}><div className="simple-form-head"><div className="simple-form-number"><UserPlus size={18}/></div><div><span>{edit?"EDITAR CLIENTE":"NUEVO CLIENTE"}</span><h2>{edit?"Corregí los datos que necesites.":"¿A quién le vas a trabajar?"}</h2><p>Con el nombre alcanza para empezar. Teléfono y email ayudan para compartir y contactar.</p></div><button type="button" className="icon-close" onClick={cancel} aria-label="Cerrar"><X size={17}/></button></div>
   <div className="simple-fields"><label className="field field-big">Nombre o empresa<input autoFocus className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej. Juan Pérez / Taller Norte" required/></label><label className="field">Teléfono <small>opcional</small><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Ej. 11 5555 5555"/></label><label className="field">Email <small>opcional</small><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="cliente@email.com"/></label></div>
   <details className="optional-fields"><summary>Agregar CUIT, dirección o notas <ChevronDown size={14}/></summary><div className="form-grid"><label className="field">CUIT / documento<input className="input" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></label><label className="field">Dirección<input className="input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="field full">Notas<textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Algo que quieras recordar de este cliente."/></label></div></details>
   {error&&<div className="error">{error}</div>}<div className="simple-form-actions"><button className="btn btn-light" type="button" onClick={cancel}>Cancelar</button><button className="btn btn-brand" disabled={busy}>{busy?"Guardando...":edit?"Guardar cambios":"Guardar cliente"}</button></div>
  </form>}
  <section className="manager-list-v3"><div className="manager-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente..."/></div>{filtered.length===0?<div className="simple-empty large"><UsersPlaceholder/><b>{clients.length===0?"Todavía no cargaste clientes.":"No encontramos ese cliente."}</b>{clients.length===0&&<button className="btn btn-brand" onClick={()=>setShow(true)}>Agregar el primero</button>}</div>:filtered.map(c=><article className="simple-list-row" key={c.id}><Link className="simple-list-main" href={"/dashboard/cliente/"+c.id}><div className="avatar-letter">{c.name.charAt(0).toUpperCase()}</div><div><b>{c.name}</b><span>{c.phone||c.email||c.taxId||"Sin datos de contacto"}</span>{c.address&&<small>{c.address}</small>}</div></Link><div className="row-actions"><Link className="btn btn-light" href={"/dashboard/cliente/"+c.id} aria-label="Abrir cliente"><ExternalLink size={13}/></Link><button className="btn btn-light" onClick={()=>start(c)} aria-label="Editar"><Pencil size={13}/></button><button className="btn btn-light danger-quiet" onClick={()=>del(c.id)} aria-label="Eliminar"><Trash2 size={13}/></button></div></article>)}</section>
 </div>
}
function UsersPlaceholder(){return <div className="empty-icon"><UserPlus size={22}/></div>}