"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {Pencil,Trash2} from "lucide-react";
type Client={id:string;name:string;email:string|null;phone:string|null;taxId:string|null;address:string|null;notes:string|null};
const blank={name:"",email:"",phone:"",document:"",address:"",notes:""};
export function ClientManager(){const r=useRouter();const[clients,setClients]=useState<Client[]>([]);const[form,setForm]=useState(blank);const[edit,setEdit]=useState<string|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function load(){const x=await fetch("/api/clients");const j=await x.json();setClients(j.clients||[])}useEffect(()=>{load()},[]);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch(edit?"/api/clients/"+edit:"/api/clients",{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await res.json();if(!res.ok)throw new Error(j.error);setForm(blank);setEdit(null);await load();r.refresh()}catch(e){setError(e instanceof Error?e.message:"Error")}finally{setBusy(false)}}
function start(c:Client){setEdit(c.id);setForm({name:c.name,email:c.email||"",phone:c.phone||"",document:c.taxId||"",address:c.address||"",notes:c.notes||""});window.scrollTo({top:0,behavior:"smooth"})}
async function del(id:string){if(!confirm("¿Eliminar este cliente? Las constancias existentes se conservan."))return;await fetch("/api/clients/"+id,{method:"DELETE"});await load();r.refresh()}
return <><form className="panel form" onSubmit={submit}><h2>{edit?"Editar cliente":"Nuevo cliente"}</h2><div className="form-grid"><label className="field">Nombre<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label className="field">Email<input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field">Teléfono<input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field">CUIT / documento<input className="input" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></label><label className="field full">Dirección<input className="input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="field full">Notas<textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<div className="error">{error}</div>}<div className="actions">{edit&&<button className="btn btn-light" type="button" onClick={()=>{setEdit(null);setForm(blank)}}>Cancelar</button>}<button className="btn btn-brand" disabled={busy}>{busy?"Guardando...":"Guardar cliente"}</button></div></form><section className="table-card">{clients.length===0?<p className="muted" style={{padding:24}}>Todavía no hay clientes.</p>:clients.map(c=><div className="table-row" style={{gridTemplateColumns:"1fr 180px 80px"}} key={c.id}><div><b>{c.name}</b><div className="muted">{c.email||c.phone||c.taxId||"Sin datos adicionales"}</div></div><span>{c.address||""}</span><div style={{display:"flex",gap:4}}><button className="btn btn-light" onClick={()=>start(c)}><Pencil size={13}/></button><button className="btn btn-light" onClick={()=>del(c.id)}><Trash2 size={13}/></button></div></div>)}</section></>}
