import {ArrowRight,Check,ClipboardCheck,MapPin,PackageCheck,Wrench} from "lucide-react";
import Link from "next/link";

const steps=[
 {n:"01",ey:"CLIENTE + ACTIVO",title:"Empezá con el contexto correcto.",text:"Creás el cliente una sola vez y vinculás cada equipo, máquina, vehículo o instalación. A partir de ahí, todo el historial queda ordenado.",bullets:["Ficha 360° del cliente","QR individual por activo","Serie, ubicación, garantía e historial"],type:"client"},
 {n:"02",ey:"PRESUPUESTO + ORDEN",title:"De lo comercial a la operación.",text:"Armás el presupuesto, lo compartís y, cuando se aprueba, el trabajo pasa a orden con responsable, prioridad, fecha y materiales.",bullets:["Presupuesto compartible","Orden programada","Técnico y prioridad"],type:"order"},
 {n:"03",ey:"TRABAJO EN CAMPO",title:"El técnico documenta mientras trabaja.",text:"Desde el celular inicia la orden, registra GPS, completa el checklist, carga evidencia Antes / Durante / Después y deja notas técnicas.",bullets:["Checklist obligatorio","GPS de inicio y fin","Fotos por etapa"],type:"field"},
 {n:"04",ey:"CIERRE VERIFICABLE",title:"La constancia nace del trabajo real.",text:"Al finalizar, el cliente firma y queda una constancia profesional con documento, IP, dispositivo, fotos, QR, PDF, garantía y próximo service.",bullets:["Firma + documento","QR y PDF","Trazabilidad completa"],type:"certificate"},
 {n:"05",ey:"COBRO + CUENTA CORRIENTE",title:"Documentar también ayuda a cobrar.",text:"Registrás pagos parciales o generás un link de Mercado Pago. El saldo se actualiza y queda un recibo asociado al trabajo.",bullets:["Saldo pendiente","Mercado Pago","Recibo imprimible"],type:"payment"},
 {n:"06",ey:"RECURRENCIA",title:"El cierre de hoy dispara el próximo trabajo.",text:"Programás el próximo service o un contrato recurrente. Constancia lo lleva a agenda y puede generar la siguiente orden automáticamente.",bullets:["Próximo service","Contratos recurrentes","OT automática"],type:"recurrence"},
];

function Shot({type}:{type:string}){
 if(type==="client")return <div className="guide-shot"><div className="shot-toolbar"><i/><i/><i/><span>Cliente · Metalúrgica Norte</span></div><div className="shot-body"><div className="shot-side"><b>MN</b><span>Cliente activo</span><small>CUIT · Teléfono · Email</small></div><div className="shot-main"><div className="shot-kpis"><span><b>3</b> Activos</span><span><b>8</b> Trabajos</span><span><b>$95k</b> Saldo</span></div><div className="shot-asset"><PackageCheck size={18}/><div><b>A-00001 · Compresor Atlas</b><small>GA 15 · AC-845921 · Planta 1</small></div><em>QR</em></div><div className="shot-line"/><div className="shot-line short"/></div></div></div>;
 if(type==="order")return <div className="guide-shot"><div className="shot-toolbar"><i/><i/><i/><span>OT-00001 · Programada</span></div><div className="shot-body single"><div className="shot-order-head"><div><small>CLIENTE</small><b>Metalúrgica Norte</b></div><span>PRIORIDAD NORMAL</span></div><h4>Mantenimiento preventivo trimestral</h4><div className="shot-grid"><div><small>TÉCNICO</small><b>Tu equipo</b></div><div><small>FECHA</small><b>Hoy · 14:30</b></div><div><small>ACTIVO</small><b>Compresor principal</b></div><div><small>MATERIAL</small><b>Filtro x1</b></div></div><button>ABRIR ORDEN <ArrowRight size={12}/></button></div></div>;
 if(type==="field")return <div className="guide-shot phone-shot"><div className="phone-shell"><div className="phone-top">10:42 <span>● ● ●</span></div><div className="phone-content"><small>OT-00001 · EN CURSO</small><h4>Mantenimiento preventivo</h4><div className="gps-pill"><MapPin size={11}/> GPS registrado</div><div className="check-row"><Check size={12}/><span>Controlar filtro</span></div><div className="check-row"><Check size={12}/><span>Revisar conexiones</span></div><div className="photo-stage"><span>ANTES</span><div><i/><i/><i/></div></div><div className="photo-stage"><span>DURANTE</span><div><i/><i/></div></div><button>FINALIZAR EJECUCIÓN</button></div></div></div>;
 if(type==="certificate")return <div className="guide-shot document-shot"><div className="doc-paper"><div className="doc-top"><div><small>CONSTANCIA DE SERVICIO</small><b>#000001</b></div><span>VERIFICADA</span></div><h4>Mantenimiento preventivo trimestral</h4><p>Se realizó limpieza general, cambio de filtro, control y prueba operativa.</p><div className="doc-info"><span><small>CLIENTE</small><b>Metalúrgica Norte</b></span><span><small>PRÓXIMO SERVICE</small><b>29/10/2026</b></span></div><div className="doc-sign"><div>firma</div><div className="fake-qr">QR</div></div></div></div>;
 if(type==="payment")return <div className="guide-shot"><div className="shot-toolbar"><i/><i/><i/><span>Cobro del trabajo</span></div><div className="shot-body single payment-shot"><small>TOTAL DEL TRABAJO</small><strong>$185.000</strong><div className="payment-progress"><i/></div><div className="payment-cols"><span><small>ABONADO</small><b>$90.000</b></span><span><small>SALDO</small><b>$95.000</b></span></div><button>COBRAR CON MERCADO PAGO</button><em>El pago se concilia automáticamente</em></div></div>;
 return <div className="guide-shot"><div className="shot-toolbar"><i/><i/><i/><span>Agenda operativa</span></div><div className="shot-body single recurrence-shot"><div className="recurrence-date"><span>HOY</span><b>01</b><small>OCT</small></div><div className="recurrence-card"><Wrench size={18}/><div><small>CONTRATO</small><b>Abono preventivo trimestral</b><span>Metalúrgica Norte · Compresor principal</span></div></div><div className="recurrence-arrow">↓</div><div className="recurrence-card green"><ClipboardCheck size={18}/><div><small>ORDEN AUTOMÁTICA</small><b>OT-00002 creada</b><span>Próxima visita programada</span></div></div></div></div>
}

export function PublicProcessShowcase(){
 return <section id="guia" className="section process-section"><div className="container"><div className="process-title"><div><div className="eyebrow">MIRÁ CÓMO SE USA</div><h2>De cero a trabajo cobrado, paso por paso.</h2></div><p>No hace falta imaginarlo. Este es el recorrido real que hace una empresa dentro de Constancia.</p></div><div className="process-list">{steps.map((s,i)=><article className="process-row" key={s.n}><div className="process-copy"><span className="process-number">{s.n}</span><div className="eyebrow">{s.ey}</div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.bullets.map(x=><li key={x}><Check size={13}/>{x}</li>)}</ul>{i===2&&<Link href="/registro" className="text-link">Probar este flujo gratis <ArrowRight size={13}/></Link>}</div><Shot type={s.type}/></article>)}</div></div></section>
}
