"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";import {ChevronDown,FilePlus2,Plus,Search,Share2,X} from "lucide-react";
type Client={id:string;name:string};type Item={description:string;quantity:string;unitPrice:string};type Row={id:string;sequentialNumber:number;publicCode:string;title:string;status:string;validUntil:string|null;totalAmountCents:string;client:{name:string}};
const statusLabel:Record<string,string>={DRAFT:"Borrador",SENT:"Enviado",APPROVED:"Aprobado",REJECTED:"Rechazado",EXPIRED:"Vencido",CONVERTED:"Trabajo creado"};
export function QuoteManager({clients}:{clients:Client[]}){
 const rtr=useRouter();const[rows,setRows]=useState<Row[]>([]);const[clientId,setClient]=useState("");const[title,setTitle]=useState("");const[notes,setNotes]=useState("");const[validUntil,setValid]=useState("");const[items,setItems]=useState<Item[]>([{description:"",quantity:"1",unitPrice:""}]);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[show,setShow]=useState(false);const[q,setQ]=useState("");
 async function load(){const r=await fetch("/api/quotes");const j=await r.json();const list=j.quotes||[];setRows(list);if(list.length===0&&clients.length>0)setShow(true)}useEffect(()=>{load();if(location.hash==="#nuevo")setShow(true)},[]);
 const total=useMemo(()=>items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.unitPrice)||0),0),[items]);
 const filtered=useMemo(()=>rows.filter(x=>[x.title,x.client.name,statusLabel[x.status]].join(" ").toLowerCase().includes(q.toLowerCase())),[rows,q]);
 function update(i:number,key:keyof Item,value:string){setItems(x=>x.map((it,n)=>n===i?{...it,[key]:value}:it))}
 function reset(){setClient("");setTitle("");setNotes("");setValid("");setItems([{description:"",quantity:"1",unitPrice:""}]);setShow(false);setError("")}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId,title,notes,validUntil,items})});const j=await r.json();if(!r.ok)throw new Error(j.error);reset();await load()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el presupuesto.")}finally{setBusy(false)}}
 async function convert(id:string){const r=await fetch("/api/quotes/"+id+"/convert",{method:"POST"});const j=await r.json();if(r.ok){rtr.push("/dashboard/orden/"+j.id);rtr.refresh()}}
 if(clients.length===0)return <section className="prerequisite-card"><div className="empty-icon"><FilePlus2 size={23}/></div><div><span className="eyebrow">PRIMERO UN CLIENTE</span><h2>Para presupuestar necesitás saber a quién.</h2><p>Creá el cliente y después volvés acá.</p></div><Link className="btn btn-brand" href="/dashboard/clientes#nuevo">Crear cliente</Link></section>;
 return <div className="manager-v3"><section className="manager-toolbar"><div><b>{rows.length} presupuesto{rows.length===1?"":"s"}</b><span>Cotizá, compartí el link y convertí lo aprobado en trabajo.</span></div><button className="btn btn-brand" onClick={()=>setShow(true)}><Plus size={14}/>Nuevo presupuesto</button></section>
 {show&&<form id="nuevo" className="panel form simple-form-card" onSubmit={submit}><div className="simple-form-head"><div className="simple-form-number"><FilePlus2 size={18}/></div><div><span>NUEVO PRESUPUESTO</span><h2>¿Qué le vas a cotizar?</h2><p>Elegí el cliente, poné un título y cargá lo que vas a cobrar.</p></div><button type="button" className="icon-close" onClick={reset}><X size={17}/></button></div>
 <div className="simple-fields"><label className="field field-big">Cliente<select className="select" required value={clientId} onChange={e=>setClient(e.target.value)}><option value="">Elegí un cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field field-big">¿Qué trabajo es?<input className="input" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Service y cambio de filtro"/></label></div>
 <div className="quote-simple-items"><div className="quote-simple-head"><b>¿Qué incluye?</b><span>Total: <strong>$ {total.toLocaleString("es-AR",{maximumFractionDigits:2})}</strong></span></div>{items.map((it,i)=><div className="quote-item-v3" key={i}><label><span>Descripción</span><input className="input" placeholder="Ej. Service completo" required value={it.description} onChange={e=>update(i,"description",e.target.value)}/></label><label className="qty"><span>Cant.</span><input className="input" type="number" min=".001" step=".001" required value={it.quantity} onChange={e=>update(i,"quantity",e.target.value)}/></label><label><span>Precio</span><input className="input" type="number" min="0" step=".01" placeholder="0" required value={it.unitPrice} onChange={e=>update(i,"unitPrice",e.target.value)}/></label>{items.length>1&&<button type="button" className="remove-item" onClick={()=>setItems(x=>x.filter((_,n)=>n!==i))}>×</button>}</div>)}<button type="button" className="add-simple-item" onClick={()=>setItems(x=>[...x,{description:"",quantity:"1",unitPrice:""}])}><Plus size={13}/>Agregar otra cosa</button></div>
 <details className="optional-fields"><summary>Agregar vencimiento o una nota <ChevronDown size={14}/></summary><div className="form-grid"><label className="field">Válido hasta<input className="input" type="date" value={validUntil} onChange={e=>setValid(e.target.value)}/></label><label className="field full">Nota para el cliente<textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Condiciones, aclaraciones, forma de pago..."/></label></div></details>
 {error&&<div className="error">{error}</div>}<div className="simple-form-actions"><button type="button" className="btn btn-light" onClick={reset}>Cancelar</button><button className="btn btn-brand" disabled={busy}>{busy?"Creando...":"Crear presupuesto"}</button></div></form>}
 <section className="manager-list-v3"><div className="manager-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar presupuesto..."/></div>{filtered.length===0?<div className="simple-empty large"><div className="empty-icon"><FilePlus2 size={22}/></div><b>{rows.length===0?"Todavía no hiciste presupuestos.":"No encontramos coincidencias."}</b></div>:filtered.map(x=><article className="simple-list-row" key={x.id}><div className="quote-number">P-{String(x.sequentialNumber).padStart(4,"0")}</div><div className="simple-list-main static"><div><b>{x.title}</b><span>{x.client.name} · {statusLabel[x.status]||x.status}</span></div></div><strong className="list-money">$ {(Number(x.totalAmountCents)/100).toLocaleString("es-AR",{maximumFractionDigits:2})}</strong><div className="row-actions"><Link className="btn btn-light" href={"/presupuesto/"+x.publicCode} target="_blank"><Share2 size={13}/>Compartir</Link>{!["CONVERTED","REJECTED"].includes(x.status)&&<button className="btn btn-brand" type="button" onClick={()=>convert(x.id)}>Crear trabajo</button>}</div></article>)}</section></div>
}