"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {ChevronDown,ClipboardPlus,Plus,Search,X} from "lucide-react";

type Client={id:string;name:string};
type Asset={id:string;clientId:string;name:string;assetNumber:number};
type Member={id:string;name:string};
type Template={id:string;name:string;defaultTitle:string;defaultDescription:string;defaultDurationMinutes:number|null};
type Row={id:string;sequentialNumber:number;title:string;status:string;priority:string;scheduledStart:string|null;client:{name:string};asset:{name:string}|null;assignedUser:{name:string}|null;certificate:{id:string}|null};

const labels:Record<string,string>={SCHEDULED:"Programado",EN_ROUTE:"En camino",IN_PROGRESS:"Trabajando",WAITING_PART:"Esperando repuesto",COMPLETED:"Terminado",CANCELED:"Cancelado"};
const blank={clientId:"",assetId:"",templateId:"",assignedUserId:"",priority:"NORMAL",title:"",description:"",serviceAddress:"",scheduledStart:"",scheduledEnd:"",internalNotes:""};

export function WorkOrderManager({clients,assets,members,templates}:{clients:Client[];assets:Asset[];members:Member[];templates:Template[]}){
 const r=useRouter();const[rows,setRows]=useState<Row[]>([]);const[form,setForm]=useState(blank);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[show,setShow]=useState(false);const[q,setQ]=useState("");
 const filteredAssets=useMemo(()=>assets.filter(a=>!form.clientId||a.clientId===form.clientId),[assets,form.clientId]);
 const filteredRows=useMemo(()=>rows.filter(w=>[w.title,w.client.name,w.asset?.name,w.assignedUser?.name,labels[w.status]].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function load(){const x=await fetch("/api/work-orders");const j=await x.json();const list=j.workOrders||[];setRows(list);if(list.length===0&&clients.length>0)setShow(true)}
 useEffect(()=>{load();if(location.hash==="#nuevo")setShow(true)},[]);
 function chooseTemplate(id:string){const t=templates.find(x=>x.id===id);setForm(v=>({...v,templateId:id,title:t?.defaultTitle||v.title,description:t?.defaultDescription||v.description}))}
 function reset(){setForm(blank);setShow(false);setError("")}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/work-orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,description:form.description.trim()||form.title.trim()})});const j=await res.json();if(!res.ok)throw new Error(j.error);reset();await load();r.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el trabajo.")}finally{setBusy(false)}}
 if(clients.length===0)return <section className="prerequisite-card"><div className="empty-icon"><ClipboardPlus size={23}/></div><div><span className="eyebrow">PRIMERO UN CLIENTE</span><h2>¿Para quién es el trabajo?</h2><p>Creá el cliente. Después volvés acá y el resto es rápido.</p></div><Link className="btn btn-brand" href="/dashboard/clientes#nuevo">Crear cliente</Link></section>;
 return <div className="manager-v3"><section className="manager-toolbar"><div><b>{rows.filter(x=>!["COMPLETED","CANCELED"].includes(x.status)).length} trabajo{rows.length===1?"":"s"} abierto{rows.length===1?"":"s"}</b><span>Crealo con lo básico. El técnico completa evidencia y cierre después.</span></div><button className="btn btn-brand" onClick={()=>setShow(true)}><Plus size={14}/>Nuevo trabajo</button></section>
 {show&&<form id="nuevo" className="panel form simple-form-card" onSubmit={submit}><div className="simple-form-head"><div className="simple-form-number"><ClipboardPlus size={18}/></div><div><span>NUEVO TRABAJO</span><h2>¿Qué hay que hacer?</h2><p>Cliente, tarea y fecha. Todo lo demás es opcional.</p></div><button type="button" className="icon-close" onClick={reset}><X size={17}/></button></div>
 <div className="work-simple-grid">
  <label className="field step-field"><span className="step-label"><i>1</i>Cliente</span><select className="select" value={form.clientId} required onChange={e=>setForm({...form,clientId:e.target.value,assetId:""})}><option value="">Elegí un cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  <label className="field step-field"><span className="step-label"><i>2</i>¿Qué hay que hacer?</span><input className="input" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ej. Revisar aire que no enfría"/></label>
  <label className="field step-field"><span className="step-label"><i>3</i>¿Cuándo?</span><input className="input" type="datetime-local" value={form.scheduledStart} onChange={e=>setForm({...form,scheduledStart:e.target.value})}/><small>Podés dejarlo sin fecha.</small></label>
  <label className="field step-field"><span className="step-label"><i>4</i>¿Quién lo hace?</span><select className="select" value={form.assignedUserId} onChange={e=>setForm({...form,assignedUserId:e.target.value})}><option value="">Lo asigno después</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
 </div>
 <label className="field full work-description">Detalle <small>opcional pero recomendado</small><textarea className="textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Contá qué pidió el cliente o qué debería revisar el técnico."/></label>
 <details className="optional-fields"><summary>Equipo, plantilla, dirección, prioridad y más <ChevronDown size={14}/></summary><div className="form-grid"><label className="field">Equipo / activo<select className="select" value={form.assetId} onChange={e=>setForm({...form,assetId:e.target.value})}><option value="">Sin equipo específico</option>{filteredAssets.map(a=><option key={a.id} value={a.id}>A-{String(a.assetNumber).padStart(5,"0")} · {a.name}</option>)}</select></label><label className="field">Usar plantilla<select className="select" value={form.templateId} onChange={e=>chooseTemplate(e.target.value)}><option value="">Sin plantilla</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">Prioridad<select className="select" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="NORMAL">Normal</option><option value="LOW">Baja</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select></label><label className="field">Fin estimado<input className="input" type="datetime-local" value={form.scheduledEnd} onChange={e=>setForm({...form,scheduledEnd:e.target.value})}/></label><label className="field full">Dirección del trabajo<input className="input" value={form.serviceAddress} onChange={e=>setForm({...form,serviceAddress:e.target.value})}/></label><label className="field full">Nota interna<textarea className="textarea" value={form.internalNotes} onChange={e=>setForm({...form,internalNotes:e.target.value})}/></label></div></details>
 {error&&<div className="error">{error}</div>}<div className="simple-form-actions"><button type="button" className="btn btn-light" onClick={reset}>Cancelar</button><button className="btn btn-brand" disabled={busy}>{busy?"Creando...":"Crear trabajo"}</button></div></form>}
 <section className="manager-list-v3"><div className="manager-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar trabajo, cliente o técnico..."/></div>{filteredRows.length===0?<div className="simple-empty large"><div className="empty-icon"><ClipboardPlus size={22}/></div><b>{rows.length===0?"Todavía no creaste trabajos.":"No encontramos coincidencias."}</b></div>:filteredRows.map(w=><Link href={"/dashboard/orden/"+w.id} className="simple-list-row work-row-v3" key={w.id}><div className="quote-number">OT-{String(w.sequentialNumber).padStart(4,"0")}</div><div className="simple-list-main static"><div><b>{w.title}</b><span>{w.client.name}{w.asset?" · "+w.asset.name:""}{w.assignedUser?" · "+w.assignedUser.name:""}</span></div></div><span className="work-date">{w.scheduledStart?new Date(w.scheduledStart).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"Sin fecha"}</span><span className={"pill wo-"+w.status.toLowerCase()}>{labels[w.status]||w.status}</span></Link>)}</section></div>
}