import {createHmac,timingSafeEqual} from "crypto";import {Plan} from "@prisma/client";import {PLAN_INFO} from "@/lib/plans";import {appUrl} from "@/lib/utils";
const API="https://api.mercadopago.com";
function token(){if(!process.env.MERCADOPAGO_ACCESS_TOKEN)throw new Error("Mercado Pago no está configurado");return process.env.MERCADOPAGO_ACCESS_TOKEN}
async function mp<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(API+path,{...init,headers:{Authorization:"Bearer "+token(),"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error("Mercado Pago "+r.status+": "+JSON.stringify(body));return body as T}
export async function createSubscription(plan:Exclude<Plan,"FREE">,email:string,organizationId:string){const p=PLAN_INFO[plan];return mp<{id:string;init_point:string;status:string}>("/preapproval",{method:"POST",body:JSON.stringify({reason:"Constancia - Plan "+p.name,external_reference:"constancia:"+organizationId+":"+plan,payer_email:email,auto_recurring:{frequency:1,frequency_type:"months",transaction_amount:p.monthly,currency_id:"ARS"},back_url:appUrl("/dashboard/facturacion?mp=return"),status:"pending"})})}
export function getSubscription(id:string){return mp<any>("/preapproval/"+encodeURIComponent(id))}
export function getAuthorizedPayment(id:string){return mp<any>("/authorized_payments/"+encodeURIComponent(id))}
export function getPayment(id:string){return mp<any>("/v1/payments/"+encodeURIComponent(id))}
export function cancelSubscription(id:string){return mp<any>("/preapproval/"+encodeURIComponent(id),{method:"PUT",body:JSON.stringify({status:"canceled"})})}
export function validMpSignature(request:Request,dataId:string){const secret=process.env.MERCADOPAGO_WEBHOOK_SECRET;if(!secret)return false;const signature=request.headers.get("x-signature")||"";const requestId=request.headers.get("x-request-id")||"";const parts=Object.fromEntries(signature.split(",").map(x=>x.trim().split("=",2)));if(!parts.ts||!parts.v1||!requestId)return false;const manifest="id:"+dataId.toLowerCase()+";request-id:"+requestId+";ts:"+parts.ts+";";const expected=createHmac("sha256",secret).update(manifest).digest("hex");const a=Buffer.from(expected),b=Buffer.from(parts.v1);return a.length===b.length&&timingSafeEqual(a,b)}
