import Link from "next/link";import {db} from "@/lib/db";import {activeOrganization} from "@/lib/org";
const dayKey=(d:Date)=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");
export default async function Agenda(){
 const{organization}=await activeOrganization();const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);const until=new Date(start);until.setDate(until.getDate()+45);
 const[orders,services,contracts]=await Promise.all([
  db.workOrder.findMany({where:{organizationId:organization.id,status:{notIn:["COMPLETED","CANCELED"]},scheduledStart:{gte:new Date(start.getTime()-86400000),lte:until}},include:{client:true,asset:true,assignedUser:true},orderBy:{scheduledStart:"asc"}}),
  db.certificate.findMany({where:{organizationId:organization.id,status:"ISSUED",nextServiceAt:{gte:start,lte:until}},include:{client:true,asset:true},orderBy:{nextServiceAt:"asc"}}),
  db.maintenanceContract.findMany({where:{organizationId:organization.id,status:"ACTIVE",nextVisitAt:{gte:start,lte:until}},include:{client:true,asset:true},orderBy:{nextVisitAt:"asc"}})
 ]);
 const items=[...orders.map(x=>({date:x.scheduledStart!,kind:"OT",title:x.title,sub:x.client.name+(x.asset?" · "+x.asset.name:"")+(x.assignedUser?" · "+x.assignedUser.name:""),href:"/dashboard/orden/"+x.id})),...services.map(x=>({date:x.nextServiceAt!,kind:"SERVICE",title:x.serviceTitle,sub:(x.client?.name||"Sin cliente")+(x.asset?" · "+x.asset.name:""),href:"/dashboard/constancia/"+x.id})),...contracts.map(x=>({date:x.nextVisitAt!,kind:"CONTRACT",title:x.name,sub:x.client.name+(x.asset?" · "+x.asset.name:""),href:"/dashboard/contratos"}))].sort((a,b)=>+a.date-+b.date);
 const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d});const weekEnd=new Date(start);weekEnd.setDate(weekEnd.getDate()+7);const later=items.filter(x=>x.date>=weekEnd);
 return <><header className="page-head"><div><div className="eyebrow">AGENDA OPERATIVA</div><h1>La semana a la vista.</h1><p>Órdenes, próximos services y visitas de contratos en una sola línea de tiempo.</p></div><Link className="btn btn-brand" href="/dashboard/ordenes">Nueva orden</Link></header>
 <section className="calendar-board">{days.map((d,i)=>{const list=items.filter(x=>dayKey(x.date)===dayKey(d));return <div className={"calendar-day "+(i===0?"today":"")} key={dayKey(d)}><div className="calendar-day-head"><span>{i===0?"HOY":d.toLocaleDateString("es-AR",{weekday:"short"}).toUpperCase()}</span><b>{d.getDate()}</b><small>{d.toLocaleDateString("es-AR",{month:"short"})}</small></div><div className="calendar-day-body">{list.length===0?<span className="calendar-empty">Libre</span>:list.map((x,n)=><Link href={x.href} className={"calendar-event event-"+x.kind.toLowerCase()} key={n}><time>{x.date.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</time><b>{x.title}</b><small>{x.sub}</small><em>{x.kind==="OT"?"Orden":x.kind==="CONTRACT"?"Contrato":"Service"}</em></Link>)}</div></div>})}</section>
 <section className="table-card"><div className="panel-table-head"><div><b>Después de esta semana</b><span>Próximos 45 días</span></div></div>{later.length===0?<p className="muted" style={{padding:24}}>No hay movimientos posteriores programados.</p>:later.map((x,i)=><Link href={x.href} className="agenda-item" style={{border:0,borderBottom:"1px solid var(--line)",borderRadius:0}} key={x.kind+i+x.href}><div className="agenda-date"><b>{x.date.toLocaleDateString("es-AR",{day:"2-digit",month:"short"})}</b><span>{x.date.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</span></div><div><span className="pill">{x.kind==="OT"?"Orden":x.kind==="CONTRACT"?"Contrato":"Próximo service"}</span><h3>{x.title}</h3><p>{x.sub}</p></div></Link>)}</section></>
}