import { certificatePdfBuffer } from "../lib/certificate-pdf";

const now = new Date();
const certificate = {
  id: "smoke-certificate",
  organizationId: "smoke-org",
  clientId: "smoke-client",
  createdByUserId: "smoke-user",
  sequentialNumber: 1,
  code: "SMOKE-VERIFY-CODE",
  status: "ISSUED",
  serviceTitle: "Mantenimiento preventivo",
  description: "Prueba automática de generación PDF para Constancia.",
  observations: "Documento generado por CI.",
  technicianName: "Técnico QA",
  serviceAddress: "Bragado, Buenos Aires",
  performedAt: now,
  nextServiceAt: new Date(now.getTime() + 30 * 86400000),
  reminderSentAt: null,
  signatureDataUrl: null,
  signatureName: "Cliente QA",
  customerAcceptedAt: null,
  totalAmountCents: 15000000n,
  currency: "ARS",
  paymentStatus: "PARTIAL",
  paymentDueDate: new Date(now.getTime() + 7 * 86400000),
  paymentReminderSentAt: null,
  paymentNotes: "Saldo contra entrega.",
  createdAt: now,
  updatedAt: now,
  organization: {
    id: "smoke-org",
    name: "Servicios QA",
    legalName: "Servicios QA S.A.",
    cuit: "30-00000000-0",
    email: "qa@example.com",
    phone: null,
    address: null,
    logoUrl: null,
    publicSlug: "servicios-qa",
    plan: "PRO",
    monthlyCertificateLimit: 500,
    subscriptionStatus: "ACTIVE",
    mpSubscriptionId: null,
    mpPayerEmail: null,
    subscriptionCurrentEnd: null,
    createdAt: now,
    updatedAt: now,
  },
  client: {
    id: "smoke-client",
    organizationId: "smoke-org",
    name: "Cliente QA",
    email: "cliente@example.com",
    phone: null,
    taxId: "20-00000000-0",
    address: null,
    notes: null,
    createdAt: now,
    updatedAt: now,
  },
  photos: [],
  servicePayments: [{
    id: "smoke-payment",
    certificateId: "smoke-certificate",
    amountCents: 5000000n,
    method: "BANK_TRANSFER",
    paidAt: now,
    reference: "QA-001",
    notes: null,
    createdByUserId: "smoke-user",
    createdAt: now,
  }],
} as any;

const buffer = await certificatePdfBuffer(certificate);
if (buffer.length < 1500) throw new Error("PDF demasiado pequeño");
if (buffer.subarray(0, 5).toString("ascii") !== "%PDF-") throw new Error("Salida inválida: no es PDF");
console.log("PDF smoke OK", buffer.length);
