import Link from "next/link";
import {ArrowRight,BookOpen,CheckCircle2,ClipboardCheck,FileCheck2,FileText,PackageCheck,ReceiptText,Repeat2,Smartphone,UsersRound} from "lucide-react";

const sections=[
 {I:UsersRound,title:"1. Crear cliente",text:"Cargá los datos básicos de la empresa o persona. Esa ficha va a concentrar activos, trabajos, constancias, presupuestos, contratos y cuenta corriente.",href:"/dashboard/clientes",cta:"Ir a Clientes",steps:["Nuevo cliente","Nombre y contacto","CUIT / documento","Dirección y notas"]},
 {I:PackageCheck,title:"2. Cargar equipo o activo",text:"Asociá cada máquina, vehículo, equipo o instalación al cliente. El QR individual abre su identidad e historial.",href:"/dashboard/activos",cta:"Ir a Activos",steps:["Elegir cliente","Marca / modelo / serie","Ubicación","QR + historial"]},
 {I:FileText,title:"3. Presupuestar",text:"Armá el trabajo con ítems, cantidades y precios. Compartilo y usalo como punto de partida para la ejecución.",href:"/dashboard/presupuestos",cta:"Ir a Presupuestos",steps:["Crear presupuesto","Agregar ítems","Compartir link","Aprobación"]},
 {I:ClipboardCheck,title:"4. Programar y ejecutar",text:"La orden concentra técnico, prioridad, materiales, checklist, GPS, horarios, notas y evidencia fotográfica.",href:"/dashboard/ordenes",cta:"Ir a Órdenes",steps:["Programar OT","Asignar técnico","Iniciar + GPS","Checklist + fotos","Finalizar"]},
 {I:FileCheck2,title:"5. Emitir constancia",text:"Cuando la ejecución está cerrada, emitís la constancia con firma, documento, evidencia, QR, PDF, garantía y próximo service.",href:"/dashboard/constancias",cta:"Ver Constancias",steps:["OT completada","Emitir constancia","Firma","QR / PDF","Próximo service"]},
 {I:ReceiptText,title:"6. Cobrar y seguir saldo",text:"Registrá pagos manuales o cobrales con Mercado Pago. El saldo queda en Caja y en la cuenta corriente del cliente.",href:"/dashboard/caja",cta:"Ir a Caja",steps:["Importe","Pago parcial o total","Recibo","Saldo / cuenta corriente"]},
 {I:Repeat2,title:"7. Hacerlo recurrente",text:"Creá contratos o abonos para que la próxima visita aparezca en agenda y genere una nueva orden automáticamente.",href:"/dashboard/contratos",cta:"Ir a Contratos",steps:["Frecuencia","Próxima visita","Agenda","OT automática"]},
];

export default function GuidePage(){return <><header className="page-head"><div><div className="eyebrow">GUÍA OPERATIVA</div><h1>Cómo usar Constancia.</h1><p>El recorrido completo, desde el primer cliente hasta el próximo service.</p></div><Link href="/dashboard" className="btn btn-light"><BookOpen size={14}/> Volver al resumen</Link></header>
<section className="guide-intro-panel"><div><Smartphone size={22}/><div><b>Podés hacer todo este recorrido desde el celular.</b><span>El técnico usa la misma cuenta para abrir la orden, registrar GPS, completar checklist, cargar fotos y cerrar el trabajo.</span></div></div><Link href="/dashboard" className="text-link">Ver datos de ejemplo <ArrowRight size={13}/></Link></section>
<div className="dashboard-guide-grid">{sections.map(({I,title,text,href,cta,steps})=><article className="dashboard-guide-card" key={title}><div className="dashboard-guide-icon"><I size={19}/></div><h2>{title}</h2><p>{text}</p><div className="dashboard-guide-steps">{steps.map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><CheckCircle2 size={13}/></div>)}</div><Link href={href} className="btn btn-light">{cta}<ArrowRight size={13}/></Link></article>)}</div>
<section className="guide-final-panel"><div><div className="eyebrow">ATAJO</div><h2>Si todavía tenés los datos demo, recorré primero el ejemplo completo.</h2><p>Está armado justamente para que veas cómo se relacionan cliente, activo, orden, constancia, pago y próximo service.</p></div><Link href="/dashboard" className="btn btn-brand">Ir al ejemplo <ArrowRight size={14}/></Link></section></>}