import Link from "next/link";
import {ArrowUpRight,CalendarDays,CircleDollarSign,ClipboardList,FilePlus2,FileText,HelpCircle,PackageSearch,UserPlus,UsersRound,Wrench} from "lucide-react";
import {db} from "@/lib/db";import {activeOrganization} from "@/lib/org";import {moneyCents} from "@/lib/utils";import {DemoOnboarding} from "@/components/DemoOnboarding";import {DemoStarter} from "@/components/DemoStarter";import {DEMO_MARKER} from "@/lib/demo-data";

const statusLabels:Record<string,string>={SCHEDULED:"Programada",EN_ROUTE:"En camino",IN_PROGRESS:"En curso",WAITING_PART:"Esperando repuesto",COMPLETED:"Completada",CANCELED:"Cancelada"};
export default async function Dashboard(){
 const{organization}=await activeOrganization();const now=new Date();const monthStart=new Date(now.getFullYear(),now.getMonth(),1);const todayStart=new Date(now);todayStart.setHours(0,0,0,0);const tomorrow=new Date(todayStart);tomorrow.setDate(tomorrow.getDate()+1);const next7=new Date(todayStart);next7.setDate(next7.getDate()+7);
 const[clients,assets,orders,certs,payments,todayOrders,upcoming,contracts,demoClients]=await Promise.all([
  db.client.count({where:{organizationId:organization.id}}),
  db.asset.count({where:{organizationId:organization.id,status:"ACTIVE"}}),
  db.workOrder.findMany({where:{organizationId:organization.id},include:{client:true,asset:true,assignedUser:true},orderBy:{createdAt:"desc"},take:100}),
  db.certificate.findMany({where:{organizationId:organization.id,status:{not:"VOID"}},include:{client:true,asset:true,servicePayments:true,workOrder:{include:{materials:true}}},orderBy:{createdAt:"desc"},take:300}),
  db.certificatePayment.findMany({where:{certificate:{organizationId:organization.id},paidAt:{gte:monthStart}},select:{amountCents:true}}),
  db.workOrder.findMany({where:{organizationId:organization.id,status:{notIn:["COMPLETED","CANCELED"]},scheduledStart:{gte:todayStart,lt:tomorrow}},include:{client:true,asset:true,assignedUser:true},orderBy:{scheduledStart:"asc"}}),
  db.workOrder.findMany({where:{organizationId:organization.id,status:{notIn:["COMPLETED","CANCELED"]},scheduledStart:{gte:tomorrow,lte:next7}},include:{client:true,asset:true},orderBy:{scheduledStart:"asc"},take:6}),
  db.maintenanceContract.count({where:{organizationId:organization.id,status:"ACTIVE"}}),
  db.client.count({where:{organizationId:organization.id,notes:{contains:DEMO_MARKER}}})
 ]);
 const monthCerts=certs.filter(c=>c.createdAt>=monthStart);const billed=monthCerts.reduce((s,c)=>s+(c.totalAmountCents||0n),0n);const collected=payments.reduce((s,p)=>s+p.amountCents,0n);
 const outstanding=certs.reduce((s,c)=>{if(c.totalAmountCents===null)return s;const paid=c.servicePayments.reduce((a,p)=>a+p.amountCents,0n);return s+(c.totalAmountCents>paid?c.totalAmountCents-paid:0n)},0n);
 const openOrders=orders.filter(x=>!["COMPLETED","CANCELED"].includes(x.status));const inProgress=orders.filter(x=>x.status==="IN_PROGRESS").length;
 const materialCost=monthCerts.reduce((sum,c)=>sum+(c.workOrder?.materials||[]).reduce((s,m)=>s+(m.unitCostCents?BigInt(Math.round(Number(m.quantity)*1000))*m.unitCostCents/1000n:0n),0n),0n);
 const margin=billed>materialCost?billed-materialCost:0n;const collectionRate=billed>0n?Math.min(100,Math.round(Number(collected*10000n/billed)/100)):0;
 const dueSoon=certs.filter(c=>c.nextServiceAt&&c.nextServiceAt>=now&&c.nextServiceAt<=next7).length;
 const showDemoStarter=demoClients===0&&clients===0&&assets===0&&orders.length===0&&certs.length===0;
 return <>{demoClients>0&&<DemoOnboarding/>}{showDemoStarter&&<DemoStarter/>}<header className="page-head dashboard-head"><div><div className="eyebrow">CENTRO DE OPERACIONES</div><h1>{organization.name}</h1><p>Una vista rápida de trabajo, caja y próximos movimientos.</p></div><div className="dashboard-actions"><Link className="btn btn-light" href="/dashboard/ordenes"><ClipboardList size={14}/> Nueva orden</Link><Link className="btn btn-brand" href="/dashboard/nueva">Nueva constancia</Link></div></header>
 <section className="quick-action-dock"><div><span>ACCIONES RÁPIDAS</span><b>Empezá donde estás.</b></div><Link href="/dashboard/clientes"><UserPlus size={15}/>Cliente</Link><Link href="/dashboard/activos"><PackageSearch size={15}/>Activo</Link><Link href="/dashboard/presupuestos"><FileText size={15}/>Presupuesto</Link><Link href="/dashboard/ordenes"><ClipboardList size={15}/>Orden</Link><Link href="/dashboard/nueva"><FilePlus2 size={15}/>Constancia</Link><Link href="/dashboard/guia" className="quick-help"><HelpCircle size={15}/>Guía</Link></section>
 <section className="kpi-grid">
  <div className="kpi-card"><span><CircleDollarSign size={15}/> Facturado este mes</span><strong>{moneyCents(billed)}</strong><small>{collectionRate}% cobrado</small><div className="kpi-track"><i style={{width:collectionRate+"%"}}/></div></div>
  <div className="kpi-card"><span><CircleDollarSign size={15}/> Cobrado este mes</span><strong>{moneyCents(collected)}</strong><small>Saldo total {moneyCents(outstanding)}</small></div>
  <div className="kpi-card"><span><Wrench size={15}/> Margen operativo</span><strong>{moneyCents(margin)}</strong><small>Facturado − materiales cargados</small></div>
  <div className="kpi-card"><span><CalendarDays size={15}/> Hoy</span><strong>{todayOrders.length}</strong><small>{inProgress} trabajo{inProgress===1?"":"s"} en curso</small></div>
 </section>
 <section className="ops-strip"><Link href="/dashboard/clientes"><UsersRound size={18}/><div><b>{clients}</b><span>Clientes</span></div><ArrowUpRight size={14}/></Link><Link href="/dashboard/activos"><PackageSearch size={18}/><div><b>{assets}</b><span>Activos</span></div><ArrowUpRight size={14}/></Link><Link href="/dashboard/ordenes"><ClipboardList size={18}/><div><b>{openOrders.length}</b><span>Órdenes abiertas</span></div><ArrowUpRight size={14}/></Link><Link href="/dashboard/contratos"><CalendarDays size={18}/><div><b>{contracts}</b><span>Contratos activos</span></div><ArrowUpRight size={14}/></Link><Link href="/dashboard/notificaciones"><Wrench size={18}/><div><b>{dueSoon}</b><span>Services esta semana</span></div><ArrowUpRight size={14}/></Link></section>
 <div className="dashboard-grid">
  <section className="panel dashboard-panel"><div className="panel-title-row"><h2>Trabajo de hoy</h2><Link href="/dashboard/agenda">Agenda completa</Link></div>{todayOrders.length===0?<div className="empty-state">No hay órdenes programadas para hoy.</div>:todayOrders.map(w=><Link className="today-job" href={"/dashboard/orden/"+w.id} key={w.id}><time>{w.scheduledStart?.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</time><div><b>{w.title}</b><small>{w.client.name}{w.asset?" · "+w.asset.name:""}{w.assignedUser?" · "+w.assignedUser.name:""}</small></div><span className={"pill wo-"+w.status.toLowerCase()}>{statusLabels[w.status]||w.status}</span></Link>)}</section>
  <section className="panel dashboard-panel"><div className="panel-title-row"><h2>Próximos 7 días</h2><Link href="/dashboard/agenda">Ver todo</Link></div>{upcoming.length===0?<div className="empty-state">Semana despejada.</div>:upcoming.map(w=><Link className="upcoming-job" href={"/dashboard/orden/"+w.id} key={w.id}><div className="date-box"><b>{w.scheduledStart?.toLocaleDateString("es-AR",{day:"2-digit"})}</b><span>{w.scheduledStart?.toLocaleDateString("es-AR",{month:"short"})}</span></div><div><b>{w.title}</b><small>{w.client.name}{w.asset?" · "+w.asset.name:""}</small></div></Link>)}</section>
 </div>
 <section className="table-card"><div className="panel-table-head"><div><b>Últimos trabajos documentados</b><span>Constancias recientes y estado de cobro</span></div><Link href="/dashboard/constancias">Ver todas</Link></div>{certs.length===0?<p className="muted" style={{padding:24}}>Todavía no emitiste constancias.</p>:certs.slice(0,8).map(c=>{const paid=c.servicePayments.reduce((s,p)=>s+p.amountCents,0n);const balance=c.totalAmountCents===null?null:c.totalAmountCents>paid?c.totalAmountCents-paid:0n;return <Link className="table-row" key={c.id} href={"/dashboard/constancia/"+c.id}><span className="money">#{String(c.sequentialNumber).padStart(6,"0")}</span><div><b>{c.serviceTitle}</b><div className="muted">{c.client?.name||"Sin cliente"}{c.asset?" · "+c.asset.name:""}</div></div><span>{c.performedAt.toLocaleDateString("es-AR")}</span><span className={"pill "+(balance&&balance>0n?"pending":"paid")}>{balance&&balance>0n?"Saldo "+moneyCents(balance,c.currency):c.totalAmountCents===null?"Sin importe":"Pagado"}</span></Link>})}</section></>
}