import Link from "next/link";import {notFound} from "next/navigation";import {db} from "@/lib/db";import {activeOrganization} from "@/lib/org";import {moneyCents} from "@/lib/utils";import {ClientPortalTools} from "@/components/ClientPortalTools";
const statusLabel:Record<string,string>={SCHEDULED:"Programada",EN_ROUTE:"En camino",IN_PROGRESS:"En curso",WAITING_PART:"Esperando repuesto",COMPLETED:"Completada",CANCELED:"Cancelada"};
export default async function ClientDetail({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const{organization}=await activeOrganization();const client=await db.client.findFirst({where:{id,organizationId:organization.id},include:{
  assets:{where:{status:"ACTIVE"},orderBy:{assetNumber:"asc"}},
  certificates:{where:{status:{not:"VOID"}},include:{servicePayments:true,asset:true},orderBy:{performedAt:"desc"}},
  maintenanceContracts:{where:{status:"ACTIVE"},orderBy:{nextVisitAt:"asc"}},
  workOrders:{include:{asset:true,assignedUser:true},orderBy:{createdAt:"desc"},take:8},
  quotes:{orderBy:{createdAt:"desc"},take:8}
 }});if(!client)notFound();
 const billed=client.certificates.reduce((s,c)=>s+(c.totalAmountCents??0n),0n);const paid=client.certificates.reduce((s,c)=>s+c.servicePayments.reduce((a,p)=>a+p.amountCents,0n),0n);const outstanding=billed>paid?billed-paid:0n;
 const overdue=client.certificates.reduce((s,c)=>{if(!c.paymentDueDate||c.paymentDueDate>=new Date()||c.totalAmountCents===null)return s;const p=c.servicePayments.reduce((a,x)=>a+x.amountCents,0n);return s+(c.totalAmountCents>p?c.totalAmountCents-p:0n)},0n);
 const upcoming=client.certificates.filter(c=>c.nextServiceAt&&c.nextServiceAt>=new Date()).sort((a,b)=>Number(a.nextServiceAt)-Number(b.nextServiceAt));
 const ledger=[...client.certificates.filter(c=>c.totalAmountCents!==null).map(c=>({date:c.performedAt,type:"CHARGE",text:c.serviceTitle,amount:c.totalAmountCents||0n,href:"/dashboard/constancia/"+c.id})),...client.certificates.flatMap(c=>c.servicePayments.map(p=>({date:p.paidAt,type:"PAYMENT",text:"Pago · "+c.serviceTitle,amount:p.amountCents,href:"/dashboard/recibo/"+p.id})))].sort((a,b)=>+b.date-+a.date).slice(0,12);
 return <><header className="page-head"><div><Link href="/dashboard/clientes" className="muted" style={{fontSize:11}}>← Volver a clientes</Link><div className="eyebrow" style={{marginTop:12}}>FICHA 360° DEL CLIENTE</div><h1>{client.name}</h1><p>{[client.email,client.phone,client.taxId].filter(Boolean).join(" · ")||"Sin datos adicionales"}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><ClientPortalTools clientId={client.id} phone={client.phone} initialCode={client.portalCode}/><Link className="btn btn-light" href="/dashboard/cuentas">Cuenta corriente</Link><Link className="btn btn-brand" href={"/dashboard/nueva?client="+client.id}>Nueva constancia</Link></div></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Trabajos documentados</span><strong>{client.certificates.length}</strong><small>{client.workOrders.filter(x=>!["COMPLETED","CANCELED"].includes(x.status)).length} órdenes abiertas</small></div><div className="kpi-card"><span>Activos</span><strong>{client.assets.length}</strong><small>{client.maintenanceContracts.length} contratos activos</small></div><div className="kpi-card"><span>Facturado histórico</span><strong>{moneyCents(billed)}</strong><small>Cobrado {moneyCents(paid)}</small></div><div className="kpi-card"><span>Saldo pendiente</span><strong>{moneyCents(outstanding)}</strong><small>{overdue>0n?"Vencido "+moneyCents(overdue):"Sin deuda vencida"}</small></div></section>
 <div className="client-360-grid">
  <section className="panel"><div className="panel-title-row"><h2>Datos y contacto</h2></div><dl className="detail-list"><div><dt>Email</dt><dd>{client.email||"—"}</dd></div><div><dt>Teléfono</dt><dd>{client.phone||"—"}</dd></div><div><dt>CUIT / documento</dt><dd>{client.taxId||"—"}</dd></div><div><dt>Dirección</dt><dd>{client.address||"—"}</dd></div><div className="full-detail"><dt>Notas</dt><dd>{client.notes||"—"}</dd></div></dl></section>
  <section className="panel"><div className="panel-title-row"><h2>Equipos / activos</h2><Link href="/dashboard/activos">Administrar</Link></div>{client.assets.length===0?<p className="muted">No hay activos registrados.</p>:client.assets.slice(0,7).map(a=><Link key={a.id} href={"/dashboard/activo/"+a.id} className="mini-list-row"><div><b>A-{String(a.assetNumber).padStart(5,"0")} · {a.name}</b><small>{[a.brand,a.model,a.serialNumber].filter(Boolean).join(" · ")||a.category||"Activo"}</small></div><span>→</span></Link>)}</section>
  <section className="panel"><div className="panel-title-row"><h2>Órdenes recientes</h2><Link href="/dashboard/ordenes">Ver órdenes</Link></div>{client.workOrders.length===0?<p className="muted">Sin órdenes.</p>:client.workOrders.map(w=><Link className="mini-list-row" href={"/dashboard/orden/"+w.id} key={w.id}><div><b>OT-{String(w.sequentialNumber).padStart(5,"0")} · {w.title}</b><small>{w.asset?.name||"Sin activo"}{w.assignedUser?" · "+w.assignedUser.name:""}</small></div><span className={"pill wo-"+w.status.toLowerCase()}>{statusLabel[w.status]||w.status}</span></Link>)}</section>
  <section className="panel"><div className="panel-title-row"><h2>Presupuestos</h2><Link href="/dashboard/presupuestos">Ver todos</Link></div>{client.quotes.length===0?<p className="muted">Sin presupuestos.</p>:client.quotes.map(q=><Link className="mini-list-row" href="/dashboard/presupuestos" key={q.id}><div><b>P-{String(q.sequentialNumber).padStart(5,"0")} · {q.title}</b><small>{q.createdAt.toLocaleDateString("es-AR")} · {q.status}</small></div><b className="money">{moneyCents(q.totalAmountCents,q.currency)}</b></Link>)}</section>
  <section className="panel"><div className="panel-title-row"><h2>Próximos services</h2></div>{upcoming.length===0?<p className="muted">No hay services futuros programados.</p>:upcoming.slice(0,7).map(c=><Link key={c.id} href={"/dashboard/constancia/"+c.id} className="mini-list-row"><div><b>{c.serviceTitle}</b><small>{c.asset?.name||"Sin activo"}</small></div><b>{c.nextServiceAt!.toLocaleDateString("es-AR")}</b></Link>)}</section>
  <section className="panel"><div className="panel-title-row"><h2>Contratos activos</h2></div>{client.maintenanceContracts.length===0?<p className="muted">Sin abonos activos.</p>:client.maintenanceContracts.map(x=><div key={x.id} className="mini-list-row"><div><b>{x.name}</b><small>Cada {x.frequencyDays} días{x.nextVisitAt?" · próxima "+x.nextVisitAt.toLocaleDateString("es-AR"):""}</small></div>{x.monthlyAmountCents&&<b className="money">{moneyCents(x.monthlyAmountCents)}/mes</b>}</div>)}</section>
 </div>
 <section className="table-card"><div className="panel-table-head"><div><b>Cuenta corriente</b><span>Cargos y pagos más recientes</span></div><Link href="/dashboard/cuentas">Ver cuentas</Link></div>{ledger.length===0?<p className="muted" style={{padding:24}}>Sin movimientos.</p>:ledger.map((x,i)=><Link className="ledger-row" href={x.href} key={i}><time>{x.date.toLocaleDateString("es-AR")}</time><span className={"ledger-type "+x.type.toLowerCase()}>{x.type==="CHARGE"?"Cargo":"Pago"}</span><b>{x.text}</b><strong className="money">{x.type==="PAYMENT"?"− ":"+ "}{moneyCents(x.amount)}</strong></Link>)}</section>
 </>}